name: CI

on:
  - push
  - workflow_dispatch

env:
  REGISTRY: ghcr.io

permissions:
  packages: write
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
  image-build-push:
    uses: thejaxon/workflows/.github/workflows/image-build-push.yaml@main
    secrets: inherit
    with:
      image_name: kong-oidc
      image_tag: 1.0.0
      registry_username: ${{ github.actor }}
      docker_context: "{{defaultContext}}"
